<?php if($this->isProtected()){?>
    <div class="notification-global" style="background-color: #FFE9E9;">
        <span id="cookie-restrict"><strong><?php echo $this->helper('creativestyle_dev')->__('Currently, website is cookie-protected - it cannot be reached without cookie!') ?></strong>
            <?php echo $this->helper('creativestyle_dev')->__('Click <a href="%s">here</a> to change settings.', Mage::helper("adminhtml")->getUrl('adminhtml/system_config/edit/section/dev', array('section'=>'dev'))) ?>
        </span>
    </div>

    <script type="text/javascript">
        function toggleText(){
            new Effect.toggle($('cookie-restrict'), 'Appear', {duration:2});
        }

        setInterval("toggleText()", 2000);
    </script>
<?php } ?>
