<div style="padding:5px;border: 1px solid #eee2be;background-color: #fff9e9;">
    URL for enabling site access (cookie is set):
    <div style="font-family: Courier;padding:5px;border:1px solid #CCC;background-color: white;">
        <a href="<?php echo $this->getEnableUrl();?>" style="text-decoration: none;">
            <?php echo $this->getEnableUrl();?>
        </a>
    </div>
</div>

<style>
    a#dev_csoptions-head{
        background-image: url(<?php echo $this->getSkinUrl('images/creativestyle-dev/logo.png');?>);
        background-position: 6px 1px;
        text-indent: 27px;
    }
</style>